/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/specialties': typeof SpecialtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/specialties/$slug' | '/specialties/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/specialties/$slug' | '/specialties'
  id: '__root__' | '/' | '/about' | '/specialties/$slug' | '/specialties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
